### PR TITLE
Create context

### PR DESCRIPTION
**Pull request by jackline-kaunda**

### CODE REVIEW

**Review by okothkongo — COMMENTED** [review]
what if you added a gif to show the feature in use ,it not a must be it is advisable

**Comment by Angie254** [comment]
Creating 
peek 2019-01-30 15-50

**Comment by okothkongo** [comment]
checkout the routes, am not able to create new patient on following route GET /patient/new

**Comment by Infinical** [comment]
peek 2019-01-31 10-43

**Comment by Infinical** [comment]
peek 2019-02-01 08-14

**Pull request merged**
